### ISSUE TITLE
Error about activator module

### ISSUE THREAD

**Issue by dobachi** [dobachi/ansible-hadoop#40]
Error about activator module

```
TASK: [activator_mini | make_link_default] ************************************
failed: [localhost] => {"failed": true, "parsed": false}
BECOME-SUCCESS-ksifwkmaqzcasqpzloxwmhkjrnjvijvc
Traceback (most recent call last):
  File "/home/centos/.ansible/tmp/ansible-tmp-1433080428.37-100815259231786/alternatives", line 1756, in <module>
    main()
  File "/home/centos/.ansible/tmp/ansible-tmp-1433080428.37-100815259231786/alternatives", line 126, in main
    line_name, line_mode, line_path = line.strip().split("\t")
ValueError: need more than 1 value to unpack


FATAL: all hosts have already failed -- aborting
```

**Comment by dobachi** [comment]
Solve by updating Ansible to 1.9.1
